# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideashare', '0002_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
